### ISSUE TITLE
fyi

### ISSUE THREAD

**Issue by JeffreySarnoff** [Tokazama/StaticLists.jl#2]
I like what you have done.

The standard practice with packages that are type-focused is use the plural form of the primary type name, as you have done, and define the primary type using the singular form of the package name .. so people tend to expect that StaticLists exports StaticList.

**Comment by Tokazama** [comment]
I had that thought right after I submitted it for registration, so I'll probably be changing that.

**Comment by Tokazama** [comment]
Resolved with #5
